<p><strong>Lab</strong>:
 <a href="https://blueteamlabs.online/home/challenge/log-analysis-compromised-wordpress-ce000f5b59">Log Analysis – Compromised WordPress</a></p>
<p><strong>Scenario</strong>:
One of our WordPress sites has been compromised but we&#39;re currently unsure how. The primary hypothesis is that an installed plugin was vulnerable to a remote code execution vulnerability which gave an attacker access to the underlying operating system of the server.</p>
<p><strong>Incident Timeframe:</strong>
January 12, 2021, at 15:52:41 (3:52:41 PM) UTC to  January 14, 2021, at 07:46:52 (7:46:52 AM) UTC</p>
<p><strong>Tools used</strong>: 
Visual Studio Code,  grep</p>
<p><strong>Summary:</strong>
Following the logic of the hypothesis in the scenario. The reasonable thing to look for in the access.log provided is to look for the WordPress login portal. Typically when exploiting remote code execution vulnerabilities in WordPress it requires the attacker to first have an authenticated session.</p>
<p>A quick google search shows that WordPress login file name is: wp-login.php.</p>
<p>Using  <strong>grep -n &quot;wp-login.php&quot; access.log</strong> I can see multiple URL  requests to <strong>/wp-login.php?itsec-hb-token=adminlogin</strong>. </p>
<pre><code><span class="hljs-number">68</span>:<span class="hljs-number">172.21.0.1</span> - - <span class="hljs-string">[12/Jan/2021:15:53:22 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">GET</span> /wp-login.php?redirect_to=http%3A%2F%2F172.21.0.3%2Fwp-admin%2F&amp;reauth=1 HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">4633</span> <span class="hljs-string">"-"</span> <span class="hljs-string">"Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"</span>
<span class="hljs-number">69</span>:<span class="hljs-number">172.21.0.1</span> - - <span class="hljs-string">[12/Jan/2021:15:53:22 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">GET</span> /wp-includes/css/buttons.min.css?ver=5.6 HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">1788</span> <span class="hljs-string">"http://172.21.0.3/wp-login.php?redirect_to=http%3A%2F%2F172.21.0.3%2Fwp-admin%2F&amp;reauth=1"</span> <span class="hljs-string">"Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"</span>
<span class="hljs-number">70</span>:<span class="hljs-number">172.21.0.1</span> - - <span class="hljs-string">[12/Jan/2021:15:53:22 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">GET</span> /wp-admin/css/login.min.css?ver=5.6 HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">2296</span> <span class="hljs-string">"http://172.21.0.3/wp-login.php?redirect_to=http%3A%2F%2F172.21.0.3%2Fwp-admin%2F&amp;reauth=1"</span> <span class="hljs-string">"Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"</span>
<span class="hljs-number">71</span>:<span class="hljs-number">172.21.0.1</span> - - <span class="hljs-string">[12/Jan/2021:15:53:22 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">GET</span> /wp-includes/js/zxcvbn-async.min.js?ver=1.0 HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">608</span> <span class="hljs-string">"http://172.21.0.3/wp-login.php?redirect_to=http%3A%2F%2F172.21.0.3%2Fwp-admin%2F&amp;reauth=1"</span> <span class="hljs-string">"Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"</span>
<span class="hljs-number">72</span>:<span class="hljs-number">172.21.0.1</span> - - <span class="hljs-string">[12/Jan/2021:15:53:22 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">GET</span> /wp-admin/css/forms.min.css?ver=5.6 HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">6469</span> <span class="hljs-string">"http://172.21.0.3/wp-login.php?redirect_to=http%3A%2F%2F172.21.0.3%2Fwp-admin%2F&amp;reauth=1"</span> <span class="hljs-string">"Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"</span>
</code></pre><p>I then looked up a list of  web tools used by attackers in their enumeration or exploitation process.</p>
<p><strong>grep -n -e &quot;wpscan&quot; -e &quot;dirbuster&quot; -e &quot;dirsearch&quot; -e &quot;nmap&quot; -e &quot;Burp&quot; -e &quot;ZAP&quot; -e &quot;metasploit&quot; -e &quot;sqlmap&quot; access.log</strong> </p>
<pre><code><span class="hljs-number">1364</span>:<span class="hljs-number">119.241.22.121</span> - - <span class="hljs-string">[14/Jan/2021:06:01:41 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">GET</span> / HTTP/1.1"</span> <span class="hljs-number">403</span> <span class="hljs-number">3160</span> <span class="hljs-string">"http://172.21.0.3/"</span> <span class="hljs-string">"WPScan v3.8.10 (https://wpscan.org/)"</span>
<span class="hljs-number">1528</span>:<span class="hljs-number">168.22.54.119</span> - - <span class="hljs-string">[14/Jan/2021:06:12:53 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">POST</span> /wp-login.php HTTP/1.1"</span> <span class="hljs-number">302</span> <span class="hljs-number">243</span> <span class="hljs-string">"-"</span> <span class="hljs-string">"sqlmap/1.4.11#stable (http://sqlmap.org)"</span>
</code></pre><h4 id="-january-14-2021-at-06-01-41-utc-"><em>January 14, 2021, at 06:01:41 (UTC)</em></h4>
<p>The attacker used wpscan. Wpscan is a WordPress vulnerability scanner that can be used for user enumeration and vulnerability scanning.</p>
<h4 id="-january-14-2021-at-06-12-53-utc-"><em>January 14, 2021, at 06:12:53 (UTC)</em></h4>
<p>The attacker used sqlmap. SQLMap is an open-source penetration testing tool that automates the process of detecting and exploiting SQL injection vulnerabilities in web applications</p>
<h4 id="-january-14-2021-at-06-14-00-utc-"><em>January 14, 2021, at 06:14:00 (UTC)</em></h4>
<p>A blended attack attempt is attempted</p>
<p><strong>grep -n &quot;xp_cmdshell&quot; access.log</strong>         </p>
<pre><code><span class="hljs-number">534</span>:<span class="hljs-number">168.22</span>.<span class="hljs-number">54.119</span> - - [<span class="hljs-number">14</span>/Jan/<span class="hljs-number">2021</span>:<span class="hljs-number">06</span>:<span class="hljs-number">14</span>:<span class="hljs-number">00</span> +<span class="hljs-number">0000</span>] <span class="hljs-string">"POST /wp-login.php?itsec-hb-token=adminlogin&amp;mglS=2151%2BAND%2B1%3D1%2BUNION%2BALL%2BSELECT%2B1%2CNULL%2C%27%3Cscript%3Ealert%28%22XSS%22%29%3C%2Fscript%3E%27%2Ctable_name%2BFROM%2Binformation_schema.tables%2BWHERE%2B2%3E1--%2F%2A%2A%2F%3B%2BEXEC%2Bxp_cmdshell%28%27cat%2B..%2F..%2F..%2Fetc%2Fpasswd%27%29%23 HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">2831</span> <span class="hljs-string">"-"</span> <span class="hljs-string">"Mozilla/5.0 (X11; U; Linux i686 (x86_64); ru; rv:1.8.0.3) Gecko/20060425 SUSE/1.5.0.3-7 Firefox/1.5.0.3"</span>
<span class="hljs-number">1539</span>:<span class="hljs-number">168.22</span>.<span class="hljs-number">54.119</span> - - [<span class="hljs-number">14</span>/Jan/<span class="hljs-number">2021</span>:<span class="hljs-number">06</span>:<span class="hljs-number">14</span>:<span class="hljs-number">00</span> +<span class="hljs-number">0000</span>] <span class="hljs-string">"POST /wp-login.php?itsec-hb-token=p@y&lt;\"'p@y&amp;mglS=2151%2BAND%2B1%3D1%2BUNION%2BALL%2BSELECT%2B1%2CNULL%2C%27%3Cscript%3Ealert%28%22XSS%22%29%3C%2Fscript%3E%27%2Ctable_name%2BFROM%2Binformation_schema.tables%2BWHERE%2B2%3E1--%2F%2A%2A%2F%3B%2BEXEC%2Bxp_cmdshell%28%27cat%2B..%2F..%2F..%2Fetc%2Fpasswd%27%29%23 HTTP/1.1"</span> <span class="hljs-number">403</span> <span class="hljs-number">3252</span> <span class="hljs-string">"-"</span> <span class="hljs-string">"Mozilla/5.0 (X11; U; Linux i686 (x86_64); ru; rv:1.8.0.3) Gecko/20060425 SUSE/1.5.0.3-7 Firefox/1.5.0.3"</span>
<span class="hljs-number">1540</span>:<span class="hljs-number">168.22</span>.<span class="hljs-number">54.119</span> - - [<span class="hljs-number">14</span>/Jan/<span class="hljs-number">2021</span>:<span class="hljs-number">06</span>:<span class="hljs-number">14</span>:<span class="hljs-number">01</span> +<span class="hljs-number">0000</span>] <span class="hljs-string">"POST /wp-login.php?itsec-hb-token=adminlogin&amp;mglS=2151%2BAND%2B1%3D1%2BUNION%2BALL%2BSELECT%2B1%2CNULL%2C%27%3Cscript%3Ealert%28%22XSS%22%29%3C%2Fscript%3E%27%2Ctable_name%2BFROM%2Binformation_schema.tables%2BWHERE%2B2%3E1--%2F%2A%2A%2F%3B%2BEXEC%2Bxp_cmdshell%28%27cat%2B..%2F..%2F..%2Fetc%2Fpasswd%27%29%23 HTTP/1.1"</span> <span class="hljs-number">403</span> <span class="hljs-number">3303</span> <span class="hljs-string">"-"</span> <span class="hljs-string">"Mozilla/5.0 (X11; U; Linux i686 (x86_64); ru; rv:1.8.0.3) Gecko/20060425 SUSE/1.5.0.3-7 Firefox/1.5.0.3"</span>
<span class="hljs-number">1542</span>:<span class="hljs-number">168.22</span>.<span class="hljs-number">54.119</span> - - [<span class="hljs-number">14</span>/Jan/<span class="hljs-number">2021</span>:<span class="hljs-number">06</span>:<span class="hljs-number">14</span>:<span class="hljs-number">01</span> +<span class="hljs-number">0000</span>] <span class="hljs-string">"POST /wp-login.php?itsec-hb-token=adminlogin&amp;mglS=2151%2BAND%2B1%3D1%2BUNION%2BALL%2BSELECT%2B1%2CNULL%2C%27%3Cscript%3Ealert%28%22XSS%22%29%3C%2Fscript%3E%27%2Ctable_name%2BFROM%2Binformation_schema.tables%2BWHERE%2B2%3E1--%2F%2A%2A%2F%3B%2BEXEC%2Bxp_cmdshell%28%27cat%2B..%2F..%2F..%2Fetc%2Fpasswd%27%29%23 HTTP/1.1"</span> <span class="hljs-number">403</span> <span class="hljs-number">3303</span> <span class="hljs-string">"-"</span> <span class="hljs-string">"Mozilla/5.0 (X11; U; Linux i686 (x86_64); ru; rv:1.8.0.3) Gecko/20060425 SUSE/1.5.0.3-7 Firefox/1.5.0.3"</span>
<span class="hljs-number">1543</span>:<span class="hljs-number">168.22</span>.<span class="hljs-number">54.119</span> - - [<span class="hljs-number">14</span>/Jan/<span class="hljs-number">2021</span>:<span class="hljs-number">06</span>:<span class="hljs-number">14</span>:<span class="hljs-number">01</span> +<span class="hljs-number">0000</span>] <span class="hljs-string">"POST /wp-login.php?itsec-hb-token=adminlogin&amp;mglS=2151%2BAND%2B1%3D1%2BUNION%2BALL%2BSELECT%2B1%2CNULL%2C%27%3Cscript%3Ealert%28%22XSS%22%29%3C%2Fscript%3E%27%2Ctable_name%2BFROM%2Binformation_schema.tables%2BWHERE%2B2%3E1--%2F%2A%2A%2F%3B%2BEXEC%2Bxp_cmdshell%28%27cat%2B..%2F..%2F..%2Fetc%2Fpasswd%27%29%23 HTTP/1.1"</span> <span class="hljs-number">403</span> <span class="hljs-number">3303</span> <span class="hljs-string">"-"</span> <span class="hljs-string">"Mozilla/5.0 (X11; U; Linux i686 (x86_64); ru; rv:1.8.0.3) Gecko/20060425 SUSE/1.5.0.3-7 Firefox/1.5.0.3"</span>
</code></pre><p><strong>Breakdown of blended attack attempt</strong></p>
<p>Decoded URL: </p>
<pre><code>POST /wp-login.php?itsec-hb-<span class="hljs-built_in">token</span>=adminlogin&amp;mglS=<span class="hljs-number">2151</span>+<span class="hljs-keyword">AND</span>+<span class="hljs-number">1</span>=<span class="hljs-number">1</span>+<span class="hljs-built_in">UNION</span>+ALL+<span class="hljs-built_in">SELECT</span>+<span class="hljs-number">1</span>,<span class="hljs-built_in">NULL</span>,'&lt;script&gt;alert(<span class="hljs-string">"XSS"</span>)&lt;/script&gt;',table_name+FROM+information_schema.tables+<span class="hljs-built_in">WHERE</span>+<span class="hljs-number">2</span>&gt;<span class="hljs-number">1</span>--<span class="hljs-comment">/**/</span>;+<span class="hljs-built_in">EXEC</span>+xp_cmdshell('cat+../../../etc/passwd')<span class="hljs-meta"># HTTP/1.1</span>
</code></pre><p>SQL Injection:</p>
<pre><code>itsec-hb-<span class="hljs-built_in">token</span>=adminlogin&amp;mglS=<span class="hljs-number">2151</span>+<span class="hljs-keyword">AND</span>+<span class="hljs-number">1</span>=<span class="hljs-number">1</span>+<span class="hljs-built_in">UNION</span>+ALL+<span class="hljs-built_in">SELECT</span>+<span class="hljs-number">1</span>,<span class="hljs-built_in">NULL</span>,'&lt;script&gt;alert(<span class="hljs-string">"XSS"</span>)&lt;/script&gt;',table_name+FROM+information_schema.tables+<span class="hljs-built_in">WHERE</span>+<span class="hljs-number">2</span>&gt;<span class="hljs-number">1</span>--<span class="hljs-comment">/**/</span>;
</code></pre><p>Local File Inclusion:</p>
<p><code>EXEC+xp_cmdshell(&#39;cat+../../../etc/passwd&#39;)</code></p>
<p>XSS Payload:</p>
<pre><code><span class="hljs-tag">&lt;<span class="hljs-name">script</span>&gt;</span><span class="actionscript">alert(<span class="hljs-string">"XSS"</span>)</span><span class="hljs-tag">&lt;/<span class="hljs-name">script</span>&gt;</span>
</code></pre><h4 id="-january-14-2021-at-06-26-53-utc-"><em>January 14, 2021, at 06:26:53 (UTC)</em></h4>
<p>After finding a POST request containing <strong>ee-upload-engine.php</strong> I used google to find any information about this and exploit-db was the top result. Exploit-DB, is a online platform that archives  information about security vulnerabilities and exploits. The link I clicked on was for a python script called, <strong>WordPress Plugin Simple File List 4.2.2 - Arbitrary File Upload</strong>. This Python script exploits an arbitrary file upload vulnerability in WordPress plugin &#39;Simple File List&#39; (version 4.2.2). It generates a .png file with an embedded reverse shell payload, uploads it to the target WordPress site, and then renames the file extension to .php. Upon successful exploitation, the attacker gains remote code execution on the target system.</p>
<p><strong>grep -n &quot;ee-upload-engine.php&quot; access.log</strong>     </p>
<pre><code><span class="hljs-number">1714</span>:<span class="hljs-number">119.241.22.121</span> - - <span class="hljs-string">[14/Jan/2021:06:26:53 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">POST</span> /wp-content/plugins/simple-file-list/ee-upload-engine.php HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">236</span> <span class="hljs-string">"-"</span> <span class="hljs-string">"python-requests/2.24.0"</span>
</code></pre><p>Further confirmation that this script was used by the attacker is that immediately after this POST request their is a GET request containing fr34k.png that in following Requests turns into fr34k.php</p>
<p><strong>grep -n &quot;ee-upload-engine.php&quot; access.log -A 5</strong></p>
<pre><code><span class="hljs-number">1714</span>:<span class="hljs-number">119.241.22.121</span> - - <span class="hljs-string">[14/Jan/2021:06:26:53 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">POST</span> /wp-content/plugins/simple-file-list/ee-upload-engine.php HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">236</span> <span class="hljs-string">"-"</span> <span class="hljs-string">"python-requests/2.24.0"</span>
<span class="hljs-number">1715</span>-<span class="hljs-number">119.241.22.121</span> - - <span class="hljs-string">[14/Jan/2021:06:26:53 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">GET</span> /wp-content/uploads/simple-file-list/fr34k.png HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">84690</span> <span class="hljs-string">"-"</span> <span class="hljs-string">"python-requests/2.24.0"</span>
<span class="hljs-number">1716</span>-<span class="hljs-number">119.241.22.121</span> - - <span class="hljs-string">[14/Jan/2021:06:26:53 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">POST</span> /wp-content/plugins/simple-file-list/ee-file-engine.php HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">236</span> <span class="hljs-string">"http://172.21.0.3/wp-admin/admin.php?page=ee-simple-file-list&amp;tab=file_list&amp;eeListID=1"</span> <span class="hljs-string">"python-requests/2.24.0"</span>
<span class="hljs-number">1717</span>-<span class="hljs-number">103.69.55.212</span> - - <span class="hljs-string">[14/Jan/2021:06:27:04 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">GET</span> /wp-content/uploads/simple-file-list/fr34k.php HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">1295</span> <span class="hljs-string">"-"</span> <span class="hljs-string">"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; Tablet PC 2.0)"</span>
<span class="hljs-number">1718</span>-sh: <span class="hljs-number">1</span>: /usr/sbin/sendmail: not found
<span class="hljs-number">1719</span>-<span class="hljs-number">103.69.55.212</span> - - <span class="hljs-string">[14/Jan/2021:06:27:06 +0000]</span> <span class="hljs-string">"<span class="hljs-keyword">POST</span> /wp-content/uploads/simple-file-list/fr34k.php HTTP/1.1"</span> <span class="hljs-number">200</span> <span class="hljs-number">1213</span> <span class="hljs-string">"http://172.21.0.3/wp-content/uploads/simple-file-list/fr34k.php"</span> <span class="hljs-string">"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; Tablet PC 2.0)"</span>
</code></pre><p>Conclusion:
This is the sequence of events that occurred that allowed the attacker to gain an initial foothold of the operating system hosting WordPress</p>
